mysql:
  hostname: 127.0.0.1
  username: chsir
  password: 456789
  timeout: 1
  readtime: 2.3

default:
  driver: mysql
  hostname: localhost
  database: anan
  username: root
  charset: utf8mb4
  collation: utf8mbr_unicode_ci